"""add_agent_field_to_findings

Revision ID: 7f46544b4cf9
Revises: 55159329cd63
Create Date: 2026-08-31 14:59:47.793500

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f46544b4cf9'
down_revision: Union[str, Sequence[str], None] = '55159329cd63'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scan_findings', sa.Column('is_false_positive', sa.Boolean(), nullable=False))
    op.add_column('scan_findings', sa.Column('agent_explanation', sa.String(), nullable=True))
    op.add_column('scan_findings', sa.Column('suggested_explanation', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scan_findings', 'suggested_explanation')
    op.drop_column('scan_findings', 'agent_explanation')
    op.drop_column('scan_findings', 'is_false_positive')
    # ### end Alembic commands ###
